# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lcd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *

       

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setMaximumSize(QtCore.QSize(640, 480))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 801, 71))
        self.label_3.setStyleSheet("QLabel {\n"
"        background-color: #20bf55;\n"
"\n"
"\n"
"}")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(20, 20, 751, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.text = QtWidgets.QLabel(self.centralwidget)
        self.text.setGeometry(QtCore.QRect(20, 90, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.text.setFont(font)
        self.text.setStyleSheet("QLabel {\n"
"    font-color: black:\n"
"}")
        self.text.setObjectName("text")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 801, 581))
        self.label_2.setStyleSheet("QLabel {\n"
"    background-color: #90ee90;\n"
"}")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 130, 401, 241))
        self.tableWidget.setFrameShape(QtWidgets.QFrame.VLine)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.verticalHeader().setStretchLastSection(True)
        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1.setGeometry(QtCore.QRect(20, 380, 93, 28))
        self.pushButton1.setStyleSheet("QPushButton {\n"
"    border-radius: 7px;\n"
"    background-color:lightyellow;\n"
"}\n"
"")
        self.pushButton1.setObjectName("pushButton1")
        self.Start = QtWidgets.QPushButton(self.centralwidget)
        self.Start.setGeometry(QtCore.QRect(420, 140, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.Start.setFont(font)
        self.Start.setStyleSheet("QPushButton {\n"
"    border-radius: 8px;\n"
"    background-color: #0080ff;\n"
"    font-size: 35px;\n"
"\n"
"\n"
"}")
        self.Start.setObjectName("Start")
        self.pushButton2_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton2_2.setGeometry(QtCore.QRect(420, 200, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton2_2.setFont(font)
        self.pushButton2_2.setAutoFillBackground(False)
        self.pushButton2_2.setStyleSheet("QPushButton {\n"
"    border-radius: 8px;\n"
"    background-color: #FF7F7F;\n"
"    font-size: 35px;\n"
"\n"
"\n"
"}")
        self.pushButton2_2.setObjectName("pushButton2_2")
        self.text_2 = QtWidgets.QLabel(self.centralwidget)
        self.text_2.setGeometry(QtCore.QRect(430, 310, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.text_2.setFont(font)
        self.text_2.setObjectName("text_2")
        self.counter = QtWidgets.QTableWidget(self.centralwidget)
        self.counter.setGeometry(QtCore.QRect(450, 340, 151, 51))
        self.counter.setObjectName("counter")
        self.counter.setColumnCount(0)
        self.counter.setRowCount(0)
        self.label_2.raise_()
        self.label_3.raise_()
        self.title.raise_()
        self.text.raise_()
        self.tableWidget.raise_()
        self.pushButton1.raise_()
        self.Start.raise_()
        self.pushButton2_2.raise_()
        self.text_2.raise_()
        self.counter.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "SUGARCANE NODE CUTTING MACHINE DEVICE"))
        self.text.setText(_translate("MainWindow", "DAILY LOGS"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Time"))
        self.pushButton1.setText(_translate("MainWindow", "Refresh"))
        self.Start.setText(_translate("MainWindow", "START"))
        self.pushButton2_2.setText(_translate("MainWindow", "STOP"))
        self.text_2.setText(_translate("MainWindow", "TOTAL NODE COUNTER:"))


        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
